default:
  image: gitlab-registry.cern.ch/ci-tools/docker-image-builder


stages:          # List of stages for jobs, and their order of execution
  - build



build1:      # This job runs in the deploy stage.
  stage: build  # It only runs when *both* jobs in the test stage complete successfully.
  parallel: 5
  tags:
    - gitlab-test-1
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile 

